export const SKILLS = [
  'Python',
  'TensorFlow',
  'PyTorch',
  'GPT-4',
  'OpenAI API',
  'Machine Learning',
  'Natural Language Processing',
  'Computer Vision',
  'Data Science',
  'API Integration',
  'REST APIs',
  'UiPath',
  'Automation Anywhere',
  'RPA',
  'Workflow Automation',
  'Process Mining',
  'AWS',
  'Google Cloud',
  'Azure',
  'Docker',
  'Kubernetes',
  'n8n',
  'SQL',
  'NoSQL',
  'React',
  'Node.js',
  'FastAPI',
  'Flask',
  'Django',
  'LangChain',
  'Vector Databases',
] as const;

export const LANGUAGES = [
  'English',
  'Spanish',
  'French',
  'German',
  'Chinese',
  'Japanese',
  'Czech',
  'Slovak',
  'Russian',
  'Arabic',
  'Portuguese',
  'Italian',
] as const;
