import type {
  ProjectInfo,
  ProjectMessage,
  ProjectUpdate,
  ProjectFile,
} from '../types';

export const MOCK_PROJECT: ProjectInfo = {
  id: 'project-1',
  clientId: 'client-1',
  freelancerId: 'freelancer-1',
  title: 'Customer Support AI Chatbot',
  client: 'TechCorp Solutions',
  clientAvatar: 'TC',
  freelancer: 'Alex Chen',
  freelancerAvatar: 'AC',
  budget: 18000,
  upfrontAmount: 9000,
  finalAmount: 9000,
  upfrontPaid: true,
  upfrontDate: 'Dec 15, 2024',
  finalPaid: false,
  startDate: 'Dec 15, 2024',
  deadline: 'Feb 28, 2025',
  progress: 65,
  status: 'in-progress',
  deliverables: [
    'Fully functional GPT-4 powered chatbot',
    'Integration with existing CRM system',
    'Admin dashboard for monitoring',
    'Complete API documentation',
    'Testing and deployment support',
    'User training materials',
  ],
};

export const MOCK_MESSAGES: ProjectMessage[] = [
  {
    id: 'msg-1',
    sender: 'client',
    senderName: 'Jennifer Chen',
    senderRole: 'Project Manager',
    avatar: 'JC',
    content:
      'Hi Alex! The initial model training looks great. The response accuracy has improved significantly.',
    timestamp: '10:30 AM',
    date: 'Today',
    type: 'text',
  },
  {
    id: 'msg-2',
    sender: 'freelancer',
    senderName: 'Alex Chen',
    senderRole: 'AI Engineer',
    avatar: 'AC',
    content:
      "Thank you! I'm glad you're seeing the improvements. I've uploaded the latest test results showing 94% accuracy on the validation set.",
    timestamp: '10:35 AM',
    date: 'Today',
    type: 'text',
  },
  {
    id: 'msg-3',
    sender: 'freelancer',
    senderName: 'Alex Chen',
    senderRole: 'AI Engineer',
    avatar: 'AC',
    content: 'model_performance_report.pdf',
    timestamp: '10:35 AM',
    date: 'Today',
    type: 'file',
    fileName: 'model_performance_report.pdf',
    fileSize: '2.1 MB',
  },
  {
    id: 'msg-4',
    sender: 'client',
    senderName: 'Jennifer Chen',
    senderRole: 'Project Manager',
    avatar: 'JC',
    content: 'Excellent! Can we schedule a demo for the stakeholders next week?',
    timestamp: '10:45 AM',
    date: 'Today',
    type: 'text',
  },
  {
    id: 'msg-5',
    sender: 'freelancer',
    senderName: 'Alex Chen',
    senderRole: 'AI Engineer',
    avatar: 'AC',
    content:
      "Absolutely! I'm available Tuesday or Thursday afternoon. Which works better for your team?",
    timestamp: '10:50 AM',
    date: 'Today',
    type: 'text',
  },
];

export const MOCK_UPDATES: ProjectUpdate[] = [
  {
    id: 'update-1',
    type: 'milestone_completed',
    title: 'Milestone Completed',
    description: '"Model Training & Integration" milestone completed and submitted for review',
    user: 'Alex Chen',
    avatar: 'AC',
    timestamp: '2 days ago',
    date: 'Jan 18, 2025',
  },
  {
    id: 'update-2',
    type: 'payment_released',
    title: 'Payment Released',
    description: 'Payment of $6,000 released for "Model Training & Integration"',
    user: 'TechCorp Solutions',
    avatar: 'TC',
    timestamp: '2 days ago',
    date: 'Jan 18, 2025',
  },
  {
    id: 'update-3',
    type: 'file_uploaded',
    title: 'Files Uploaded',
    description: 'Uploaded 3 new files: API documentation, integration guide, test results',
    user: 'Alex Chen',
    avatar: 'AC',
    timestamp: '3 days ago',
    date: 'Jan 17, 2025',
  },
  {
    id: 'update-4',
    type: 'milestone_started',
    title: 'Milestone Started',
    description: 'Started work on "Testing & Optimization" milestone',
    user: 'Alex Chen',
    avatar: 'AC',
    timestamp: '3 days ago',
    date: 'Jan 17, 2025',
  },
  {
    id: 'update-5',
    type: 'message',
    title: 'New Message',
    description: 'Demo scheduled for next Tuesday at 2 PM PST',
    user: 'Jennifer Chen',
    avatar: 'JC',
    timestamp: '4 days ago',
    date: 'Jan 16, 2025',
  },
  {
    id: 'update-6',
    type: 'milestone_completed',
    title: 'Milestone Completed',
    description: '"Initial Setup & Data Analysis" milestone completed',
    user: 'Alex Chen',
    avatar: 'AC',
    timestamp: '1 week ago',
    date: 'Jan 2, 2025',
  },
];

export const MOCK_FILES: ProjectFile[] = [
  {
    id: 'file-1',
    name: 'model_performance_report.pdf',
    size: '2.1 MB',
    uploadedBy: 'Alex Chen',
    date: 'Jan 18, 2025',
  },
  {
    id: 'file-2',
    name: 'api_documentation.pdf',
    size: '1.8 MB',
    uploadedBy: 'Alex Chen',
    date: 'Jan 17, 2025',
  },
  {
    id: 'file-3',
    name: 'integration_guide.pdf',
    size: '3.2 MB',
    uploadedBy: 'Alex Chen',
    date: 'Jan 17, 2025',
  },
  {
    id: 'file-4',
    name: 'test_results.xlsx',
    size: '856 KB',
    uploadedBy: 'Alex Chen',
    date: 'Jan 17, 2025',
  },
  {
    id: 'file-5',
    name: 'data_analysis_report.pdf',
    size: '4.5 MB',
    uploadedBy: 'Alex Chen',
    date: 'Jan 2, 2025',
  },
];
