import type { FreelancerOption } from '../../types';

export const CATEGORIES = [
  'AI Chatbots & Assistants',
  'Workflow Automation',
  'Machine Learning & AI Models',
  'Data Analysis & BI',
  'API Integration',
  'Process Automation (RPA)',
  'Natural Language Processing',
  'Computer Vision',
  'Predictive Analytics',
  'Custom AI Solutions',
  'AI Strategy & Consulting',
  'Model Training & Fine-tuning',
] as const;

export const SKILLS = [
  'Python',
  'TensorFlow',
  'PyTorch',
  'GPT-4',
  'OpenAI API',
  'Machine Learning',
  'Natural Language Processing',
  'Computer Vision',
  'Data Science',
  'API Integration',
  'REST APIs',
  'UiPath',
  'Automation Anywhere',
  'RPA',
  'Workflow Automation',
  'Process Mining',
  'AWS',
  'Google Cloud',
  'Azure',
  'Docker',
  'Kubernetes',
  'SQL',
  'NoSQL',
  'React',
  'Node.js',
  'FastAPI',
  'Flask',
  'Django',
  'LangChain',
  'Vector Databases',
] as const;

export const MOCK_FREELANCERS: FreelancerOption[] = [
  {
    id: '1',
    name: 'Alex Chen',
    title: 'Senior AI Engineer & ML Specialist',
    avatar: 'AC',
    rating: 4.9,
    reviewCount: 127,
    skills: ['GPT-4', 'Python', 'TensorFlow', 'NLP'],
    hourlyRate: 95,
    completedProjects: 89,
  },
  {
    id: '2',
    name: 'Maria Garcia',
    title: 'RPA & Workflow Automation Expert',
    avatar: 'MG',
    rating: 5.0,
    reviewCount: 94,
    skills: ['UiPath', 'Power Automate', 'Python'],
    hourlyRate: 85,
    completedProjects: 76,
  },
  {
    id: '3',
    name: 'David Park',
    title: 'Data Scientist & Analytics Engineer',
    avatar: 'DP',
    rating: 4.8,
    reviewCount: 156,
    skills: ['Machine Learning', 'Python', 'Tableau'],
    hourlyRate: 90,
    completedProjects: 112,
  },
  {
    id: '4',
    name: 'Sarah Johnson',
    title: 'AI Chatbot Developer',
    avatar: 'SJ',
    rating: 4.9,
    reviewCount: 83,
    skills: ['OpenAI API', 'LangChain', 'React'],
    hourlyRate: 80,
    completedProjects: 67,
  },
  {
    id: '5',
    name: 'Michael Brown',
    title: 'Computer Vision Specialist',
    avatar: 'MB',
    rating: 4.7,
    reviewCount: 71,
    skills: ['PyTorch', 'Computer Vision', 'Python'],
    hourlyRate: 88,
    completedProjects: 54,
  },
];
